### ISSUE TITLE
Restore Subscriptions Functionality and Front-End and Backend

### ISSUE THREAD

**Issue by fthobe** [solidusio-contrib/solidus_subscriptions#305]
This is a complete list of current subscription extension issues sorted by blocking issues (does not allow the effective usage of the extension) and non blocking. 

**Solidus Version**:
Current

**To Reproduce**
Install solidus with starter front-end.

**Blockers**
- [x] #304 [Breadcrumbs broken on starter front-end after installing extension](https://github.com/solidusio/solidus_subscriptions/issues/304)
- [x] #303 #243 [Subscriptions are loaded for not subscribable products](https://github.com/solidusio/solidus_subscriptions/issues/303)
- [x] #302 [Can't add subscriptions to cart: Validation failed, Subscibrable can't be blank](https://github.com/solidusio/solidus_subscriptions/issues/302)
- [x] PR #300 #294 [Depreciation Warnings](https://github.com/solidusio/solidus_subscriptions/issues/294)
- [ ] #269 #243 [Add default quantity 1 to starter front-end subscription implementation](https://github.com/solidusio/solidus_subscriptions/issues/269)
- [x] #253 [Subscriptions do not work with variants](https://github.com/solidusio/solidus_subscriptions/issues/253)
- [x] #311 

**API Completition**
- [ ] #224 [Index and Show on Subscription API](https://github.com/solidusio/solidus_subscriptions/issues/224)
- [ ] #297 [Add API Description](https://github.com/solidusio/solidus_subscriptions/issues/297)

**Non Blocking Issues**
- [ ] #297 [Add API Description](https://github.com/solidusio/solidus_subscriptions/issues/297)
- [ ] #278 [Subscriptions in cart should increase in quantity if two identical subscriptions are added](https://github.com/solidusio/solidus_subscriptions/issues/278)
- [ ] #270 [Skip subscriptions intervall](https://github.com/solidusio/solidus_subscriptions/issues/270)
- [ ] #267 [Cannot update payment methods/sources attached to a subscription](https://github.com/solidusio/solidus_subscriptions/issues/267)
- [ ] #232 [Configure Reminders](https://github.com/solidusio/solidus_subscriptions/issues/232)
- [ ] #128 [Subscriptions should work without addresses](https://github.com/solidusio/solidus_subscriptions/issues/128)

**To be discussed**
- [ ] #209 [Remove Churnbuster](https://github.com/solidusio/solidus_subscriptions/issues/209): Should be tested

**Comment by fthobe** [comment]
@jarednorman what's your oppinion on churnbuster?

**Comment by jarednorman** [comment]
I agree that the ChurnBuster integration should probably be removed.

**Comment by fthobe** [comment]
> I agree that the ChurnBuster integration should probably be removed.

Ok, we have a minor bumb to release now (and could put some notes about deprecated stuff in there and remove in the next round) and after we fixed the other stuff we can go for a major and remove / fix the remaining things.

**Comment by fthobe** [comment]
@jarednorman could you also take a look at #267 ?
